server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Ne pas cacher index.html (pour que Cloudflare serve toujours la dernière version)
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        try_files $uri /index.html;
    }

    # SPA fallback : toutes les routes renvoient index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
