name: Build & Deploy
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Determine version tag
      id: version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        else
          echo "tag=latest" >> $GITHUB_OUTPUT
        fi
    - name: Build & push API
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        platforms: linux/amd64
        push: true
        tags: |
          esgipa2rte/upcycle-api:latest
          ${{ steps.version.outputs.tag != 'latest' && format('esgipa2rte/upcycle-api:{0}', steps.version.outputs.tag) || '' }}
    - name: Build & push React
      uses: docker/build-push-action@v6
      with:
        context: ./frontend-react
        platforms: linux/amd64
        push: true
        tags: |
          esgipa2rte/upcycle-react:latest
          ${{ steps.version.outputs.tag != 'latest' && format('esgipa2rte/upcycle-react:{0}', steps.version.outputs.tag) || '' }}
    - name: Build & push Nginx
      uses: docker/build-push-action@v6
      with:
        context: ./nginx
        platforms: linux/amd64
        push: true
        tags: |
          esgipa2rte/upcycle-nginx:latest
          ${{ steps.version.outputs.tag != 'latest' && format('esgipa2rte/upcycle-nginx:{0}', steps.version.outputs.tag) || '' }}
    - name: Copy docker-compose to server
      uses: appleboy/scp-action@master
      with:
        host: 51.83.154.80
        username: debian
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2222
        source: "docker-compose.yml"
        target: "/opt/upcycleconnect"
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 51.83.154.80
        username: debian
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2222
        script: |
          cd /opt/upcycleconnect
          sed -i 's|^GMAIL_USER=.*|GMAIL_USER=${{ secrets.GMAIL_USER }}|' .env
          sed -i 's|^GMAIL_APP_PASSWORD=.*|GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}|' .env
          docker compose pull
          docker compose up -d
          echo "✅ Déploiement réussi à $(date)" >> /home/debian/deploy.log